### ISSUE TITLE
Make Debug Fully Local

### ISSUE THREAD

**Issue by miketynes** [darkreactions/ESCALATE_Capture#43]
When running in debug mode, the code still tries to connect to Google Drive

**Comment by ipendlet** [comment]
Resolved alongside #92 in the #102  branch.  The debug now runs in three levels.  Running debug in level 0 (default) will complete the whole loop.  Running on level > 0 , will download all of the offline files local and then: 

for debug = 1 will complete upload using local version of the files
for debug =2 will halt the run before pushing to google drive (but still will generate the files locally).

This solution fully resolves the offline running in debug (after the first instance of the code).
