### ISSUE TITLE
Document main datastructures

### ISSUE THREAD

**Issue by miketynes** [darkreactions/ESCALATE_Capture#46]
It would be good to have a ***brief*** writeup of what goes into all of the key dictionaries.

We have gone through it in code review, but a markdown document that simply states the structure of things like `rxndict` or `edict` so that programmers can remember what they are would be extremely helpful for our understanding of the code.

**Comment by aadharna** [comment]
This has begun here: https://github.com/darkreactions/ESCALATE_Capture/commit/4f993c6961d597873776879ab85952b6b2346076?short_path=a4d21d2#diff-a4d21d223f7240ebbfeb7870f712f5fe

**Comment by ipendlet** [comment]
This push should also aim to Improve readability of inline coding notes, coding TODOs, and documentation about installation and latest releases.

'Many of these notes and style fixes have been recorded during the most recent code review. This project should be described in more detail by @miketynes . This work is also a continuation of #24 and will be liked be resolved with the push of #46. As such this issue has been marked as resolved and this comment has been added to the #46 issue.'

**Comment by aadharna** [comment]
See Merge #59
