### ISSUE TITLE
Run UID doesn't work with current HC/LBL crystal form (now observation interface).

### ISSUE THREAD

**Issue by ipendlet** [darkreactions/ESCALATE_Capture#63]
Demo template attached

Run uid drops into the wrong column of the crystal scoring form.

Need to resolve this issue by eliminating the run uid from HC/LBL (Not a good fix)

or by ensuring that the run UID always drops into a "runUID" column of the observation interface regardless of the lab that is designing the experiment.  This could be achieved by adding the column to the first or last item of the observation interface.  (Likely will require an update to the templates of all folders, MIT, dev, LBL).  

ENsure comaptiblity with report!

**Comment by ipendlet** [comment]
[LBL_SpecificationInterface.xlsx](https://github.com/darkreactions/ESCALATE_Capture/files/3414883/LBL_SpecificationInterface.xlsx)

**Comment by miketynes** [comment]
@ipendlet Do the rows in the HC/LBL observation_interface need to be in the same order as the NIMBUS file? Or can they be in a normal, human-friendly order (A1, ..., A12, B1,..., G12)? This will change how we code this up. 

Personally, I think it makes more sense for a human-facing interface to be human-friendly. 
This is also a good time to think about distinguishing human vs NIMBUS runs.

**Comment by miketynes** [comment]
Note: we don't have to enforce that the UIDs always go to the same column, we can just put the UID column in a lab-specific config variable.
