### ISSUE TITLE
UPdate documentation, readme, history, and version numbers throughout code

### ISSUE THREAD

**Issue by ipendlet** [darkreactions/ESCALATE_Capture#65]
The most recent push still is not reflected in the versioning!

**Comment by aadharna** [comment]
see https://github.com/darkreactions/ESCALATE_Capture/compare/updateHistory

README was recently updated. if it needs more updating, what would that be?
Documentation here means what? User or Function Documentation?

**Comment by ipendlet** [comment]
Resolved. alongside #92
