### ISSUE TITLE
 old reagents code improperly overrides chemical names

### ISSUE THREAD

**Issue by ipendlet** [darkreactions/ESCALATE_Capture#88]
Chemical names in old reagents override the user specifies names (and details) even when the "subtract previous region" option is set to no. 

Example: 
[wf3_example.xlsx](https://github.com/darkreactions/ESCALATE_Capture/files/3790025/wf3_example.xlsx)

**Comment by miketynes** [comment]
This is by far the scarier issue when compared to #86.

**Comment by miketynes** [comment]
## Bad git practices lead to this issue

### Bug hunt
Testing (results: [here](https://drive.google.com/drive/u/1/folders/1CkxsTCaJqVqWBXKb_gxJKVoPgNgwwWlD)) indicates that the bug only happens in the `user_oldreagents` branch. 

A quick look at [this line](https://github.com/darkreactions/ESCALATE_Capture/compare/user_oldreagents...dev_oldreagents#diff-c93e5bd5e17ecbe6d7b8d745ac20fcb7L72) makes it obvious why this happens. 

Taking a look at the branch history we get a sense of what went on. 
![image](https://user-images.githubusercontent.com/25695528/68411174-f86e9280-0157-11ea-8077-9250df25e796.png)

The `user_oldreagents` branch is just a pointer to the merge of #84. The sept 18 commit reverts this merge. The `dev_oldreagents` branch has been rebased modified a few times and somewhere in there errors were introduced. 

### Short term path forward
My path forward will be to branch off of the #84 merge commit and move carefully forward, not making the same git mistakes that were made in `dev_oldreagents`.

### Long term solution and risk mitigation
More generally for moving forward with ESCALATE dev, I request that we always squash our feature branches before merging them to `master` and that we use squashing when rebasing. This will reduce the likelihood of similar bugs being introduced during rebases. 

Some quick intros: 
* [Squashing before merging](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges)
* [Squashing before rebasing](https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/)

@aadharna and I recall multiple *very long and tedious* rebase sessions this summer in which it was easy to make a mistake and introduce a bug. Good use of squashing will resolve this.
